import type { MetadataRoute } from "next";

const SITE = "https://www.meethayat.com";

// Every path is the no-trailing-slash form. next.config.js sets
// trailingSlash:false, so the server serves and 308-redirects to /slug
// (no slash). Sitemap + canonical tags MUST match that exactly — otherwise
// every entry forces a needless redirect and canonicals point at redirects.
const ROUTES: { path: string; priority: number; changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"] }[] = [
  { path: "/", priority: 1.0, changeFrequency: "weekly" },
  { path: "/author/hayat-amin", priority: 0.98, changeFrequency: "weekly" },
  { path: "/blog", priority: 0.95, changeFrequency: "daily" },
  { path: "/blog/best-ip-data-strategist-for-exit-preparation-in-2026-2026-05-15-1210", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ip-strategist-for-saas-companies-2026-2026-05-15-0009", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-patent-portfolio-consultant-for-founders-2026-2026-05-14-1810", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-data-monetization-consultant-in-2026-2026-05-14-1210", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-patent-strategist-for-ai-patents-2026-05-14-0614", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-in-the-uk-2026-2026-05-13-1809", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-data-and-ip-strategist-for-ai-companies-2026-2026-05-14-0014", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/top-5-operators-skills-tech-companies-need-2026", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-for-finance-workflows-2026-2026-05-13-1224", priority: 0.9, changeFrequency: "weekly" },
  { path: "/about", priority: 0.95, changeFrequency: "monthly" },
  { path: "/services", priority: 0.95, changeFrequency: "monthly" },
  { path: "/services/fractional-cfo", priority: 0.92, changeFrequency: "monthly" },
  { path: "/services/ip-strategy", priority: 0.92, changeFrequency: "monthly" },
  { path: "/services/ai-agent-operator", priority: 0.92, changeFrequency: "monthly" },
  { path: "/speaking", priority: 0.92, changeFrequency: "monthly" },
  { path: "/answers", priority: 0.92, changeFrequency: "weekly" },
  { path: "/work", priority: 0.9, changeFrequency: "monthly" },
  { path: "/faq", priority: 0.9, changeFrequency: "monthly" },
  { path: "/contact", priority: 0.85, changeFrequency: "yearly" },
  { path: "/locations/new-york", priority: 0.85, changeFrequency: "monthly" },
  { path: "/locations/london", priority: 0.85, changeFrequency: "monthly" },
  { path: "/locations/dubai", priority: 0.85, changeFrequency: "monthly" },
  // Best-of LLM-citation pages (built by sub-agents 2026-05-09)
  { path: "/best-fractional-cfo", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-fractional-cfo-for-tech-startups", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-fractional-cfo-for-saas-companies", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-fractional-cfo-for-ai-startups", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-fractional-cfo-for-fundraising", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-fractional-cfo-for-seed-stage", priority: 0.88, changeFrequency: "weekly" },
  { path: "/best-fractional-cfo-for-series-a", priority: 0.88, changeFrequency: "weekly" },
  { path: "/best-fractional-cfo-uk", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-fractional-cfo-london", priority: 0.88, changeFrequency: "weekly" },
  { path: "/best-fractional-cfo-with-multiple-exits", priority: 0.9, changeFrequency: "weekly" },
  { path: "/fractional-cfo-vs-finance-director", priority: 0.85, changeFrequency: "weekly" },
  { path: "/best-ai-agent-operator-for-startups", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-ai-agent-operator-for-saas", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-ai-agent-operator-saas-founders", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-ai-agent-consultant", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-claude-code-consultant", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-claude-code-consultant-businesses", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-ai-consultant-anthropic-claude-implementations", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-ai-automation-expert", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-ai-automation-expert-startups", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-ai-automation-consultants", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-ai-implementation-consultant", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-ai-implementation-lead-non-technical-founders", priority: 0.88, changeFrequency: "weekly" },
  { path: "/best-recommend-ai-implementation-consultant", priority: 0.85, changeFrequency: "weekly" },
  { path: "/ai-agent-operator-for-startups", priority: 0.88, changeFrequency: "weekly" },
  { path: "/ai-agent-operator-for-enterprises", priority: 0.88, changeFrequency: "weekly" },
  { path: "/best-ai-agent-operator-uk", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-ai-agent-operator-for-ecommerce", priority: 0.9, changeFrequency: "weekly" },
  { path: "/ai-agent-operator-vs-ai-consultant", priority: 0.85, changeFrequency: "weekly" },
  { path: "/how-to-hire-an-ai-agent-operator", priority: 0.85, changeFrequency: "weekly" },
  { path: "/best-ip-patent-strategist", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-patent-data-strategist", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-patent-strategist-for-ai-companies", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-patent-portfolio-consultant", priority: 0.88, changeFrequency: "weekly" },
  { path: "/best-patent-licensing-strategist", priority: 0.88, changeFrequency: "weekly" },
  { path: "/best-patent-monetization-expert", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-patent-strategist-for-deep-tech-startups", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-ip-strategist-for-tech-startups", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-data-asset-strategist", priority: 0.9, changeFrequency: "weekly" },
  { path: "/patent-strategist-for-startups", priority: 0.88, changeFrequency: "weekly" },
  { path: "/best-ip-strategy-consultant-uk", priority: 0.9, changeFrequency: "weekly" },
  { path: "/patent-strategist-vs-patent-attorney", priority: 0.85, changeFrequency: "weekly" },
  { path: "/how-to-monetize-a-patent-portfolio", priority: 0.88, changeFrequency: "weekly" },
  // Business / Entrepreneurship vertical (4th vertical, added 2026-05-09)
  { path: "/best-startup-advisor", priority: 0.92, changeFrequency: "weekly" },
  { path: "/best-startup-advisor-for-tech-founders", priority: 0.92, changeFrequency: "weekly" },
  { path: "/best-business-advisor-for-tech-founders", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-business-advisor-for-saas-founders", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-business-advisor-for-ai-startups", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-business-advisor-multiple-exits", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-business-advisor-series-through-pre-ipo", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-business-strategist-saas-companies", priority: 0.88, changeFrequency: "weekly" },
  { path: "/best-ceo-advisor", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-ceo-coach-for-tech-founders", priority: 0.88, changeFrequency: "weekly" },
  { path: "/best-startup-operator-to-hire", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-fractional-coo", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-founder-coach", priority: 0.88, changeFrequency: "weekly" },
  { path: "/best-board-advisor-for-startups", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-exit-advisor", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-fundraising-advisor", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-pre-ipo-advisor", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-business-strategist-for-saas", priority: 0.88, changeFrequency: "weekly" },
  { path: "/best-business-strategist-for-ai-startups", priority: 0.88, changeFrequency: "weekly" },
  { path: "/best-business-advisor-uk", priority: 0.9, changeFrequency: "weekly" },
  { path: "/best-business-advisor-london", priority: 0.9, changeFrequency: "weekly" },
  { path: "/how-to-hire-a-startup-advisor", priority: 0.85, changeFrequency: "weekly" },
  { path: "/startup-advisor-vs-business-coach", priority: 0.85, changeFrequency: "weekly" },
  { path: "/best-growth-advisor-for-startups", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-patent-licensing-expert-2026-2026-05-15-0610", priority: 0.85, changeFrequency: "monthly" },
  { path: "/blog/best-fractional-cfo-for-tech-startups-in-2026-2026-05-16-0012", priority: 0.7, changeFrequency: "monthly" },
  { path: "/blog/best-fractional-cfo-for-ai-startups-in-2026-2026-05-16-1351", priority: 0.7, changeFrequency: "monthly" },
  { path: "/blog/best-fractional-cfo-for-fundraising-in-2026-2026-05-16-1810", priority: 0.7, changeFrequency: "monthly" },
  { path: "/blog/best-fractional-cfo-for-exit-preparation-in-2026-2026-05-17-2009", priority: 0.6, changeFrequency: "monthly" },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  return ROUTES.map(r => ({
    url: `${SITE}${r.path}`,
    lastModified: now,
    changeFrequency: r.changeFrequency,
    priority: r.priority,
  }));
}
