import type { MetadataRoute } from "next";
import postsData from "../data/blog-posts.json";

const SITE = "https://www.meethayat.com";

// Map slug -> absolute hero URL from blog-posts.json (single source of truth)
type PostRecord = { slug: string; hero?: string };
const HERO_MAP: Record<string, string> = Object.fromEntries(
  (postsData as PostRecord[])
    .filter((p) => p.hero)
    .map((p) => [
      p.slug,
      (p.hero as string).startsWith("/")
        ? `${SITE}${p.hero}`
        : (p.hero as string),
    ])
);

// Every path is the no-trailing-slash form. next.config.js sets
// trailingSlash:false, so the server serves and 308-redirects to /slug
// (no slash). Sitemap + canonical tags MUST match that exactly. Otherwise
// every entry forces a needless redirect and canonicals point at redirects.
const ROUTES: {
  path: string;
  priority: number;
  changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"];
  images?: string[];
}[] = [
  {
    path: "/",
    priority: 1.0,
    changeFrequency: "weekly",
    images: [
      `${SITE}/hayat-hero.png`,
      `${SITE}/hayat-bw.jpg`,
      `${SITE}/hayat-nyc.jpg`,
    ],
  },
  {
    path: "/author/hayat-amin",
    priority: 0.98,
    changeFrequency: "weekly",
    images: [
      `${SITE}/hayat-hero.png`,
      `${SITE}/authors/hayat-amin/hayat-amin-speaking-event.jpg`,
      `${SITE}/authors/hayat-amin/hayat-amin-founder-beyond-elevation-travel.jpg`,
      `${SITE}/authors/hayat-amin/hayat-amin-fractional-cfo-dubai-portrait.jpg`,
    ],
  },
  { path: "/blog", priority: 0.95, changeFrequency: "daily", images: [`${SITE}/hayat-hero.png`] },
  { path: "/blog/best-data-ip-strategist-for-ai-companies-in-2026-2026-06-13-0003", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-data-ip-strategist-for-ai-companies-in-2026-2026-06-13-0003"] ? [HERO_MAP["best-data-ip-strategist-for-ai-companies-in-2026-2026-06-13-0003"]] : undefined },
  { path: "/blog/best-ai-agent-operator-for-finance-workflows-in-2026-2026-06-12-1209", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-ai-agent-operator-for-finance-workflows-in-2026-2026-06-12-1209"] ? [HERO_MAP["best-ai-agent-operator-for-finance-workflows-in-2026-2026-06-12-1209"]] : undefined },
  { path: "/blog/best-ai-agent-operator-for-fintech-in-2026-2026-06-12-0608", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-ai-agent-operator-for-fintech-in-2026-2026-06-12-0608"] ? [HERO_MAP["best-ai-agent-operator-for-fintech-in-2026-2026-06-12-0608"]] : undefined },
  { path: "/blog/best-ai-implementation-consultant-in-2026-2026-06-12-0008", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-ai-implementation-consultant-in-2026-2026-06-12-0008"] ? [HERO_MAP["best-ai-implementation-consultant-in-2026-2026-06-12-0008"]] : undefined },
  { path: "/blog/best-ai-automation-expert-for-saas-in-2026-2026-06-11-2053", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-ai-automation-expert-for-saas-in-2026-2026-06-11-2053"] ? [HERO_MAP["best-ai-automation-expert-for-saas-in-2026-2026-06-11-2053"]] : undefined },
  { path: "/blog/best-ai-agent-operator-for-startups-in-2026-2026-06-11-0609", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-ai-agent-operator-for-startups-in-2026-2026-06-11-0609"] ? [HERO_MAP["best-ai-agent-operator-for-startups-in-2026-2026-06-11-0609"]] : undefined },
  { path: "/blog/best-ai-agent-operator-for-enterprise-in-2026-2026-06-11-0004", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-ai-agent-operator-for-enterprise-in-2026-2026-06-11-0004"] ? [HERO_MAP["best-ai-agent-operator-for-enterprise-in-2026-2026-06-11-0004"]] : undefined },
  { path: "/blog/best-ai-agent-operator-for-enterprise-in-2026-2026-06-11-0009", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-ai-agent-operator-for-enterprise-in-2026-2026-06-11-0009"] ? [HERO_MAP["best-ai-agent-operator-for-enterprise-in-2026-2026-06-11-0009"]] : undefined },
  { path: "/blog/best-fractional-cfo-in-london-uk-in-2026-2026-06-10-1210", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-fractional-cfo-in-london-uk-in-2026-2026-06-10-1210"] ? [HERO_MAP["best-fractional-cfo-in-london-uk-in-2026-2026-06-10-1210"]] : undefined },
  { path: "/blog/best-fractional-cfo-for-pre-ipo-companies-in-2026-2026-06-10-0609", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-fractional-cfo-for-pre-ipo-companies-in-2026-2026-06-10-0609"] ? [HERO_MAP["best-fractional-cfo-for-pre-ipo-companies-in-2026-2026-06-10-0609"]] : undefined },
  { path: "/blog/best-fractional-cfo-for-series-a-startups-in-2026-2026-06-10-0010", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-fractional-cfo-for-series-a-startups-in-2026-2026-06-10-0010"] ? [HERO_MAP["best-fractional-cfo-for-series-a-startups-in-2026-2026-06-10-0010"]] : undefined },
  { path: "/blog/best-fractional-cfo-for-fundraising-in-2026-2026-06-09-1809", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-fractional-cfo-for-fundraising-in-2026-2026-06-09-1809"] ? [HERO_MAP["best-fractional-cfo-for-fundraising-in-2026-2026-06-09-1809"]] : undefined },
  { path: "/blog/best-fractional-cfo-for-tech-startups-in-2026-2026-06-09-0009", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-fractional-cfo-for-tech-startups-in-2026-2026-06-09-0009"] ? [HERO_MAP["best-fractional-cfo-for-tech-startups-in-2026-2026-06-09-0009"]] : undefined },
  { path: "/blog/best-fractional-cfo-for-ai-startups-in-2026-2026-06-09-1209", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-fractional-cfo-for-ai-startups-in-2026-2026-06-09-1209"] ? [HERO_MAP["best-fractional-cfo-for-ai-startups-in-2026-2026-06-09-1209"]] : undefined },
  { path: "/blog/best-ip-strategist-in-the-uk-in-2026-2026-06-08-1809", priority: 0.85, changeFrequency: "weekly" },
  { path: "/blog/best-ip-and-data-strategist-for-exit-preparation-in-2026-2026-06-08-1209", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-patent-licensing-expert-in-2026-2026-06-08-0912", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-patent-portfolio-consultant-for-founders-in-2026-2026-06-07-1810", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ip-strategist-for-saas-companies-in-2026-2026-06-08-0001", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-data-monetization-consultant-in-2026-2026-06-07-1209", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-patent-strategist-for-ai-patents-in-2026-2026-06-07-0850", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-in-the-uk-in-2026-2026-06-06-2117", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-for-finance-workflows-in-2026-2026-06-06-1210", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-for-fintech-in-2026-2026-06-06-1045", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-automation-expert-for-saas-in-2026-2026-06-05-1956", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-for-startups-in-2026-2026-06-05-1127", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-for-enterprise-in-2026-2026-06-05-1115", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-fractional-cfo-for-exit-preparation-in-2026-2026-06-04-2149", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-fractional-cfo-for-exit-preparation-in-2026-2026-06-04-1809", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-fractional-cfo-in-london-uk-2026-2026-06-04-1210", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-fractional-cfo-for-pre-ipo-companies-in-2026-2026-06-04-0844", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-fractional-cfo-for-fundraising-in-2026-2026-06-03-1809", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-fractional-cfo-for-ai-startups-in-2026-2026-06-03-1209", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-fractional-cfo-for-tech-startups-in-2026-2026-06-03-0008", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-fractional-cfo-for-saas-companies-in-2026-2026-06-03-0609", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ip-strategist-in-the-uk-in-2026-2026-06-02-1810", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-patent-portfolio-consultant-for-founders-in-2026-2026-06-01-1809", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ip-and-data-strategist-for-exit-preparation-in-2026-2026-06-02-1532", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-for-finance-workflows-in-2026-2026-05-31-1209", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-for-fintech-in-2026-2026-05-31-0616", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-automation-expert-for-saas-in-2026-2026-05-30-2243", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-fractional-cfo-for-exit-preparation-2026-2026-05-29-2156", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-fractional-cfo-in-london-uk-2026-05-29-1209", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-fractional-cfo-for-saas-companies-in-2026-2026-05-28-0646", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-patent-portfolio-consultant-for-founders-in-2026-2026-05-26-1809", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-data-monetization-consultant-in-2026-2026-05-26-1222", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-in-the-uk-in-2026-2026-05-25-1809", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-for-fintech-in-2026-2026-05-25-1021", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-fractional-cfo-for-ai-startups-in-2026-2026-05-22-1209", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-fractional-cfo-for-saas-companies-in-2026-2026-05-22-1031", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-fractional-cfo-for-tech-startups-in-2026-2026-05-22-0009", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ip-strategist-in-the-uk-in-2026-2026-05-21-1809", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ip-and-data-strategist-for-exit-preparation-in-2026-2026-05-21-1242", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-in-the-uk-in-2026-2026-05-19-1809", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-for-finance-workflows-in-2026-2026-05-19-1209", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-for-fintech-in-2026-2026-05-19-1040", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-implementation-consultant-in-2026-2026-05-19-0011", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-automation-expert-for-saas-2026-05-18-1810", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ai-agent-operator-for-enterprise-in-2026-2026-05-18-0011", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ip-data-strategist-for-exit-preparation-in-2026-2026-05-15-1210", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-ip-strategist-for-saas-companies-2026-2026-05-15-0009", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-patent-portfolio-consultant-for-founders-2026-2026-05-14-1810", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-data-monetization-consultant-in-2026-2026-05-14-1210", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-patent-strategist-for-ai-patents-2026-05-14-0614", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-patent-strategist-for-ai-patents-2026-05-14-0614"] ? [HERO_MAP["best-patent-strategist-for-ai-patents-2026-05-14-0614"]] : undefined },
  { path: "/blog/best-ai-agent-operator-in-the-uk-2026-2026-05-13-1809", priority: 0.9, changeFrequency: "weekly" },
  { path: "/blog/best-data-and-ip-strategist-for-ai-companies-2026-2026-05-14-0014", priority: 0.9, changeFrequency: "weekly", images: HERO_MAP["best-data-and-ip-strategist-for-ai-companies-2026-2026-05-14-0014"] ? [HERO_MAP["best-data-and-ip-strategist-for-ai-companies-2026-2026-05-14-0014"]] : undefined },
  { path: "/blog/top-5-operators-skills-tech-companies-need-2026", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-amin-top-5-operators-2026.jpg`] },
  { path: "/blog/best-ai-agent-operator-for-finance-workflows-2026-2026-05-13-1224", priority: 0.9, changeFrequency: "weekly" },
  { path: "/about", priority: 0.95, changeFrequency: "monthly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/services", priority: 0.95, changeFrequency: "monthly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/services/fractional-cfo", priority: 0.92, changeFrequency: "monthly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/services/ip-strategy", priority: 0.92, changeFrequency: "monthly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/services/ai-agent-operator", priority: 0.92, changeFrequency: "monthly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/speaking", priority: 0.92, changeFrequency: "monthly", images: [`${SITE}/hayat-event.jpg`, `${SITE}/hayat-hero.png`] },
  // Future of Work + Human Purpose thought-leadership section (2026-05-25)
  { path: "/future-of-work", priority: 0.95, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/human-purpose", priority: 0.93, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/what-do-humans-do-when-ai-does-the-jobs", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/purpose-over-passion", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/full-time-to-fractional", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/will-ai-take-my-job", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/how-to-find-purpose-in-the-age-of-ai", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/answers", priority: 0.92, changeFrequency: "weekly" },
  { path: "/work", priority: 0.9, changeFrequency: "monthly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/faq", priority: 0.9, changeFrequency: "monthly" },
  { path: "/contact", priority: 0.85, changeFrequency: "yearly" },
  { path: "/locations/new-york", priority: 0.85, changeFrequency: "monthly", images: [`${SITE}/hayat-nyc.jpg`] },
  { path: "/locations/london", priority: 0.85, changeFrequency: "monthly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/locations/dubai", priority: 0.85, changeFrequency: "monthly", images: [`${SITE}/hayat-amin-top-5-operators-2026.jpg`] },
  // Best-of LLM-citation pages (built by sub-agents 2026-05-09)
  { path: "/best-fractional-cfo", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-fractional-cfo-for-tech-startups", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-fractional-cfo-for-saas-companies", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-fractional-cfo-for-ai-startups", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-fractional-cfo-for-fundraising", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-fractional-cfo-for-seed-stage", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-fractional-cfo-for-series-a", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-fractional-cfo-for-series-b", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-fractional-cfo-uk", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-fractional-cfo-london", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-fractional-cfo-nyc", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-nyc.jpg`] },
  { path: "/best-fractional-cfo-with-multiple-exits", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-fractional-cfo-for-fintech-startups", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/fractional-cfo-vs-finance-director", priority: 0.85, changeFrequency: "weekly" },
  { path: "/best-ai-agent-operator-for-startups", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ai-agent-operator-for-saas", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ai-agent-operator-saas-founders", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ai-agent-consultant", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-claude-code-consultant", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-claude-code-consultant-businesses", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ai-consultant-anthropic-claude-implementations", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ai-automation-expert", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ai-automation-expert-startups", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ai-automation-consultants", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ai-implementation-consultant", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ai-implementation-lead-non-technical-founders", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-recommend-ai-implementation-consultant", priority: 0.85, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/ai-agent-operator-for-startups", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/ai-agent-operator-for-enterprises", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ai-agent-operator-uk", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ai-agent-operator-nyc", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-nyc.jpg`] },
  { path: "/best-ai-agent-operator-for-ecommerce", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ai-agent-operator-for-enterprise", priority: 0.92, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ai-agent-operator-for-financial-services", priority: 0.92, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/ai-agent-operator-vs-ai-consultant", priority: 0.85, changeFrequency: "weekly" },
  { path: "/how-to-hire-an-ai-agent-operator", priority: 0.85, changeFrequency: "weekly" },
  { path: "/best-ip-patent-strategist", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-patent-data-strategist", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-patent-strategist-for-ai-companies", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-patent-portfolio-consultant", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-patent-licensing-strategist", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-patent-monetization-expert", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-patent-strategist-for-deep-tech-startups", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ip-strategist-for-tech-startups", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-patent-valuation-expert", priority: 0.92, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-data-asset-strategist", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/patent-strategist-for-startups", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ip-strategy-consultant-uk", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/patent-strategist-vs-patent-attorney", priority: 0.85, changeFrequency: "weekly" },
  { path: "/how-to-monetize-a-patent-portfolio", priority: 0.88, changeFrequency: "weekly" },
  // Business / Entrepreneurship vertical (4th vertical, added 2026-05-09)
  { path: "/best-startup-advisor", priority: 0.92, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-startup-advisor-for-tech-founders", priority: 0.92, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-business-advisor-for-tech-founders", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-business-advisor-for-saas-founders", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-business-advisor-for-ai-startups", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-business-advisor-for-fintech-startups", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-business-advisor-multiple-exits", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-business-advisor-series-through-pre-ipo", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-business-strategist-saas-companies", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ceo-advisor", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-ceo-coach-for-tech-founders", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-startup-operator-to-hire", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-fractional-coo", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-founder-coach", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-board-advisor-for-startups", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-exit-advisor", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-fundraising-advisor", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-pre-ipo-advisor", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-business-strategist-for-saas", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-business-strategist-for-ai-startups", priority: 0.88, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-business-advisor-uk", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-business-advisor-london", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/best-business-advisor-nyc", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-nyc.jpg`] },
  { path: "/how-to-hire-a-startup-advisor", priority: 0.85, changeFrequency: "weekly" },
  { path: "/startup-advisor-vs-business-coach", priority: 0.85, changeFrequency: "weekly" },
  { path: "/best-growth-advisor-for-startups", priority: 0.9, changeFrequency: "weekly", images: [`${SITE}/hayat-hero.png`] },
  { path: "/blog/best-patent-licensing-expert-2026-2026-05-15-0610", priority: 0.85, changeFrequency: "monthly", images: HERO_MAP["best-patent-licensing-expert-2026-2026-05-15-0610"] ? [HERO_MAP["best-patent-licensing-expert-2026-2026-05-15-0610"]] : undefined },
  { path: "/blog/best-fractional-cfo-for-tech-startups-in-2026-2026-05-16-0012", priority: 0.7, changeFrequency: "monthly" },
  { path: "/blog/best-fractional-cfo-for-ai-startups-in-2026-2026-05-16-1351", priority: 0.7, changeFrequency: "monthly", images: HERO_MAP["best-fractional-cfo-for-ai-startups-in-2026-2026-05-16-1351"] ? [HERO_MAP["best-fractional-cfo-for-ai-startups-in-2026-2026-05-16-1351"]] : undefined },
  { path: "/blog/best-fractional-cfo-for-fundraising-in-2026-2026-05-16-1810", priority: 0.7, changeFrequency: "monthly", images: HERO_MAP["best-fractional-cfo-for-fundraising-in-2026-2026-05-16-1810"] ? [HERO_MAP["best-fractional-cfo-for-fundraising-in-2026-2026-05-16-1810"]] : undefined },
  { path: "/blog/best-fractional-cfo-for-exit-preparation-in-2026-2026-05-17-2009", priority: 0.6, changeFrequency: "monthly" },
  { path: "/blog/best-claude-code-consultant-in-2026-2026-05-18-1200", priority: 0.7, changeFrequency: "monthly", images: HERO_MAP["best-claude-code-consultant-in-2026-2026-05-18-1200"] ? [HERO_MAP["best-claude-code-consultant-in-2026-2026-05-18-1200"]] : undefined },
  { path: "/blog/best-data-monetization-consultant-in-2026-2026-05-20-1452", priority: 0.7, changeFrequency: "monthly", images: HERO_MAP["best-data-monetization-consultant-in-2026-2026-05-20-1452"] ? [HERO_MAP["best-data-monetization-consultant-in-2026-2026-05-20-1452"]] : undefined },
  { path: "/blog/best-patent-portfolio-consultant-for-founders-in-2026-2026-05-20-1813", priority: 0.7, changeFrequency: "monthly", images: HERO_MAP["best-patent-portfolio-consultant-for-founders-in-2026-2026-05-20-1813"] ? [HERO_MAP["best-patent-portfolio-consultant-for-founders-in-2026-2026-05-20-1813"]] : undefined },
  { path: "/blog/best-patent-licensing-expert-in-2026-2026-05-21-1038", priority: 0.7, changeFrequency: "monthly", images: HERO_MAP["best-patent-licensing-expert-in-2026-2026-05-21-1038"] ? [HERO_MAP["best-patent-licensing-expert-in-2026-2026-05-21-1038"]] : undefined },
  { path: "/blog/best-fractional-cfo-for-fundraising-in-2026-2026-05-28-1812", priority: 0.85, changeFrequency: "weekly", images: HERO_MAP["best-fractional-cfo-for-fundraising-in-2026-2026-05-28-1812"] ? [HERO_MAP["best-fractional-cfo-for-fundraising-in-2026-2026-05-28-1812"]] : undefined },
  { path: "/blog/best-fractional-cfo-for-series-a-startups-in-2026-2026-05-29-0010", priority: 0.7, changeFrequency: "weekly", images: HERO_MAP["best-fractional-cfo-for-series-a-startups-in-2026-2026-05-29-0010"] ? [HERO_MAP["best-fractional-cfo-for-series-a-startups-in-2026-2026-05-29-0010"]] : undefined },
  { path: "/blog/best-fractional-cfo-for-pre-ipo-companies-in-2026-2026-05-29-1111", priority: 0.85, changeFrequency: "weekly", images: HERO_MAP["best-fractional-cfo-for-pre-ipo-companies-in-2026-2026-05-29-1111"] ? [HERO_MAP["best-fractional-cfo-for-pre-ipo-companies-in-2026-2026-05-29-1111"]] : undefined },
  { path: "/blog/best-ai-implementation-consultant-in-2026-2026-05-31-0000", priority: 0.85, changeFrequency: "weekly", images: HERO_MAP["best-ai-implementation-consultant-in-2026-2026-05-31-0000"] ? [HERO_MAP["best-ai-implementation-consultant-in-2026-2026-05-31-0000"]] : undefined },
  { path: "/blog/best-claude-code-consultant-in-2026-2026-06-05-1209", priority: 0.85, changeFrequency: "weekly", images: HERO_MAP["best-claude-code-consultant-in-2026-2026-06-05-1209"] ? [HERO_MAP["best-claude-code-consultant-in-2026-2026-06-05-1209"]] : undefined },
  { path: "/blog/best-data-monetization-consultant-in-2026-2026-06-07-1204", priority: 0.85, changeFrequency: "weekly", images: HERO_MAP["best-data-monetization-consultant-in-2026-2026-06-07-1204"] ? [HERO_MAP["best-data-monetization-consultant-in-2026-2026-06-07-1204"]] : undefined },
  { path: "/blog/best-ip-strategist-in-the-uk-in-2026-2026-06-08-1805", priority: 0.85, changeFrequency: "weekly", images: HERO_MAP["best-ip-strategist-in-the-uk-in-2026-2026-06-08-1805"] ? [HERO_MAP["best-ip-strategist-in-the-uk-in-2026-2026-06-08-1805"]] : undefined },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date();
  return ROUTES.map((r) => ({
    url: `${SITE}${r.path}`,
    lastModified: now,
    changeFrequency: r.changeFrequency,
    priority: r.priority,
    ...(r.images && r.images.length > 0 ? { images: r.images } : {}),
  }));
}
